export const GET_APPLICATION_ID : string = "GET_APPLICATION_ID"; 
export const UPDATE_APPLICATION_ID : string = "UPDATE_APPLICATION_ID"; 
export const GET_VIDEO_CATEGORIES: string = "GET_VIDEO_CATEGORIES"; 
export const UPDATE_VIDEO_CATEGORIES: string = "UPDATE_VIDEO_CATEGORIES"; 